name: flutter_boilerplate
description: "A Flutter boilerplate project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  email_validator: ^3.0.0
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.6
  flutter_blurhash: ^0.8.2
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  hive_flutter: ^1.1.0
  home_widget: ^0.6.0
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  ios_utsname_ext: ^2.3.0
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.3
  purchases_flutter: ^6.30.2
  reorderables: ^0.6.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  universal_platform: ^1.1.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_flavorizr: ^2.2.3
  freezed: ^2.5.2
  icons_launcher: ^2.1.7
  in_app_review: ^2.0.9
  json_serializable: ^6.8.0
  rename: ^3.0.2

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - lang/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "ffffff"
  image: "assets/images/splash/splash_logo_light.png"
  color_dark: "000000"
  image_dark: "assets/images/splash/splash_logo_dark.png"
  android_12:
    image: "assets/images/splash/splash_logo_light.png"
    color: "ffffff"
    image_dark: "assets/images/splash/splash_logo_dark.png"
    icon_background_color_dark: "000000"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/capybara.png"
  remove_alpha_ios: true
